repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: name-tests-test
  - id: flake8
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: requirements-txt-fixer
  - id: fix-encoding-pragma
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.2
  hooks:
  - id: autopep8
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.2
  hooks:
  - id: reorder-python-imports
    args: [--add-import, from __future__ import absolute_import, --add-import, from __future__ import unicode_literals, --add-import, from __future__ import print_function]
    exclude: ^setup\.py$
- repo: https://github.com/asottile/pyupgrade
  rev: v1.10.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/asottile/add-trailing-comma
  rev: v0.7.1
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v1.1.3
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/Yelp/detect-secrets
  rev: 0.10.4
  hooks:
  - id: detect-secrets
    args: [--baseline, .secrets.baseline]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.641
  hooks:
  - id: mypy
    language_version: python3.6
    exclude: ^docs/.*\.py$
