swagger: '2.0'
info:
  title: Minimal Case of E008 Rule
  version: '1.0'
paths:
  /endpoint:
    get:
      responses:
        default:
          description: ''
          schema:
            properties:
              property:
                type: string
            type: object
            x-model: get_endpoint_response
    post:
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            property:
              type: string
          type: object
      responses:
        default:
          description: ''
