swagger: '2.0'
info:
  title: Minimal Case of RES-E001 Rule
  version: '1.0'
paths:
  /endpoint:
    get:
      responses:
        default:
          description: ''
          schema:
            additionalProperties: false
            properties:
              property_1:
                type: string
            type: object
            x-model: get_endpoint_response
